# Generated by Django 5.2.1 on 2025-05-24 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0003_restaurant_latitude_restaurant_longitude'),
    ]

    operations = [
        migrations.CreateModel(
            name='CuisineType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='restaurant',
            name='cuisine_type',
        ),
        migrations.AddField(
            model_name='restaurant',
            name='cuisine_types',
            field=models.ManyToManyField(related_name='restaurants', to='restaurants.cuisinetype'),
        ),
    ]
